### PR TITLE
Add MPI Hostfile support to NnfDataMovementCommandStatus

### PR DESCRIPTION
**Pull request by bdevcich-hpe**

### CODE REVIEW

**Comment by NateThornton** [comment]
Why is this needed?

**Comment by bdevcich-hpe** [comment]
For testing, for the user to understand what is contained inside the hostfile without having to shell into a pod and for being able to delete the hostfile when the NnfDataMovement is deleted.

**Comment by NateThornton** [comment]
Why would the host file be anything besides the list of Rabbits and slot count? What value is this adding? These are resources stored in a database; while a host file isn't megabytes in size, any amount makes a difference.

Why would the host file need to linger any longer than the mpirun command? Because it is deterministic, it isn't required for debugging (it can be easily reconstituted from existing resources).

**Comment by bdevcich-hpe** [comment]
> Why would the host file be anything besides the list of Rabbits and slot count? What value is this adding? These are resources stored in a database; while a host file isn't megabytes in size, any amount makes a difference.
> 
> Why would the host file need to linger any longer than the mpirun command? Because it is deterministic, it isn't required for debugging (it can be easily reconstituted from existing resources).

Because sometimes debugging is worth it's weight in gold. Since this can impact performance, I'll remove it.

**Pull request closed without merging**
